storeItemList:
  - id: '16939984552930.024336758655781443'
    name: SelectedTag
    value: ''
    valueType: string
    initialValue: ''
    version: 1
metadata:
  favicon: ''
  code: ''
  title: Accounts
  description: ''
appSettings:
  properties:
    defaultData: '{}'
  actions: {}
  gridVersion: 2
internalType: project
