id: '16968667335040.6483763399542797'
name: createPublicJoinApplicationAccounts
nameConfigured: true
steps:
  - id: '17216385359710.048300814457119756'
    type: CREATE_ENTITY
    name: create
    params:
      - type: resourceId
        value: public.join_application_accounts
        valueType: string
      - type: entity
        value: ./create-entity.yml
        valueType: custom
      - type: customDatabaseName
        value: ''
        valueType: interpolatedValue
      - type: successMapper
        value: ''
        valueType: interpolatedValue
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
      - type: mapperEnabled
        value: false
        valueType: custom
      - type: datasourceId
        value: Supabase Bridgelink Apps Database
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: true
singleStep: false
mode: manual
modeConfigured: false
parentId: null
config:
  shouldConfirm: false
  confirmMessage: >-
    Are you sure you'd like to proceed with
    "{{actions.createPublicJoinApplicationAccounts.name}}"?
  showSuccessToast: false
  successToast: >-
    Action "{{actions.createPublicJoinApplicationAccounts.name}}" successfully
    executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.createPublicJoinApplicationAccounts.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: true
kind: workflow
