id: '16969451109080.2923274468793704'
definitionId: selectWithAtomics
parentSlotId: '16969450503680.5407013159547431'
styles:
  xl:
    gridItem:
      x: 0
      y: 0
      w: 20
      h: 10
  xs:
    gridItem:
      x: 0
      y: 0
      w: 24
      h: 10
properties:
  options:
    value:
      - value: option_1
        title: ''
        __UIBAKERY__SYSTEM_ID__: '1'
      - value: option_2
        title: ''
        __UIBAKERY__SYSTEM_ID__: '2'
    dataValue: >-
      {{actions.Find_Applications.data.filter(c=>
      !ui.tbl_GenApproles.value.map(g=> g.app_id).includes(c.id)).map(x=>
      {return{title:x.app_name,value:x.id} })}}
    withData: true
  name: slct_Application
  __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
    - xl
    - xs
  optionValueKey: value
  labelConfig:
    text: Application
    position: horizontal
    align: left
  labelWidth: 15
actions:
  selectChange:
    - action: '16969457979160.5293120911869511'
      paramCode: ''
      blockPageLoad: false
      index: 0
  init: []
  focusEvent: []
  blurEvent: []
index: 0
slots:
  - id: '16969451109090.8148844249890976'
    name: optionViewTypes
    children:
      - id: '16969451109450.5500584115437264'
        definitionId: atomicString
        styles:
          xl:
            visible: true
        properties:
          name: atomicString32
          prop: title
          primaryKey: false
          __UIBAKERY__RESPONSIVE__SHOW__CONDITION__CODE__:
            - xl
            - xs
        parentSlotId: '16969451109090.8148844249890976'
        index: 1
        slots: []
