id: '16969451423520.5741608327393235'
name: Find_Applications
nameConfigured: true
steps:
  - id: '16986649235350.42347166478411147'
    type: LOAD_COLLECTION
    name: load2
    params:
      - type: datasourceId
        value: Dvelopment Database
        valueType: custom
        mustSelectFirst: true
      - type: resourceId
        value: public.applications
        valueType: custom
        mustSelectFirst: true
      - type: filters
        value: []
        valueType: custom
        interpolationType: string
      - type: ordering
        value:
          limit:
            value: 1000
          offset:
            value: ''
          orderBy:
            value: ''
          orderDirection:
            value: asc
        valueType: custom
        interpolationType: string
      - type: additionalParams
        value: []
        valueType: custom
        interpolationType: string
      - type: customDatabaseName
        value: ''
        valueType: interpolatedValue
      - type: successMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: failureMapper
        value: ''
        valueType: interpolatedValue
        interpolationType: code
      - type: mapperEnabled
        value: false
        valueType: custom
    level: 0
    fallthroughError: false
    isChanged: false
singleStep: false
mode: manual
modeConfigured: false
parentPageId: '1'
parentId: '16939972753810.5077860573161239'
config:
  shouldConfirm: false
  confirmMessage: >-
    Are you sure you'd like to proceed with
    "{{actions.Find_Applications.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.Find_Applications.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.Find_Applications.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
assigned: false
selected: true
configured: true
kind: workflow
index: 13
